# Generated by Django 3.2.11 on 2022-01-12 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0002_alter_paychannel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paychannel',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='paychannel',
            unique_together={('name', 'user')},
        ),
    ]
