version: "3.5"

services:
  db:
    image: postgres:9.6.10-alpine
    user: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DB: auth
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mfs-network

  db_pay:
    image: postgres:9.6.10-alpine
    user: postgres
    environment:
      POSTGRES_USER: docker2
      POSTGRES_PASS: docker2
      POSTGRES_DB: pay
    ports:
      - "5333:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mfs-network

  build-auth-app:
    build:
      context: ./identity
      dockerfile: Dockerfile
    image: jaodur/mfs-auth
    command: echo auth image build complete
    volumes:
      - ./identity:/app
    env_file:
      - ./identity/.env
    networks:
      - mfs-network
    depends_on:
      - db

  build-pay-app:
    build:
      context: ./pay
      dockerfile: Dockerfile
    image: jaodur/mfs-pay
    command: echo pay image build complete
    volumes:
      - ./pay:/app
    env_file:
      - ./pay/.env
    networks:
      - mfs-network
    depends_on:
      - db_pay

  migrate-auth:
    image: jaodur/mfs-auth
    command: python manage.py migrate
    volumes:
      - ./identity:/app
    env_file:
      - ./identity/.env
    networks:
      - mfs-network
    depends_on:
      - db
      - build-auth-app

  migrate-pay:
    image: jaodur/mfs-pay
    command: python manage.py migrate
    volumes:
      - ./pay:/app
    env_file:
      - ./pay/.env
    networks:
      - mfs-network
    depends_on:
      - db_pay
      - build-pay-app

  auth:
    image: jaodur/mfs-auth
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    volumes:
      - ./identity:/app
    env_file:
      - ./identity/.env
    ports:
      - "8000:8000"
    networks:
      - mfs-network
    depends_on:
      - migrate-auth

  pay:
    image: jaodur/mfs-pay
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    volumes:
      - ./pay:/app
    env_file:
      - ./pay/.env
    ports:
      - "8001:8000"
    networks:
      - mfs-network
    depends_on:
      - migrate-pay

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jaodur/mfs-frontend
    command: bash -c "npm rebuild node-sass && npm run standalone"
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
    - "5555:5555"
    env_file:
      - ./frontend/.env
    networks:
      - mfs-network


networks:
  mfs-network:
    driver: bridge

volumes:
  db_data: {}
  db2_data: {}
